"""Initial migration

Revision ID: 89c723d6b4da
Revises:
Create Date: 2026-03-17 13:00:06.909014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89c723d6b4da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock",
        sa.Column("symbol", sa.CHAR(length=6), nullable=False),
        sa.Column("date_stamp", sa.Date(), nullable=False),
        sa.Column("time_stamp", sa.Time(), nullable=True),
        sa.Column("open", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("high", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("low", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("close", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "date_stamp"),
    )
    op.create_index(op.f("ix_stock_date_stamp"), "stock", ["date_stamp"], unique=False)
    op.create_index(op.f("ix_stock_symbol"), "stock", ["symbol"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.CHAR(length=500), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_stock_symbol"), table_name="stock")
    op.drop_index(op.f("ix_stock_date_stamp"), table_name="stock")
    op.drop_table("stock")
    # ### end Alembic commands ###
